### ISSUE TITLE
[BUG] Unable to boot device in current state: Booted

### ISSUE THREAD

**Issue by Chloekkk** [JSGrowth/alarmking#11]
## Bug 개요
`yarn ios` 로 빌드 및 실행 시 나타나는 **Unable to boot device in current state: Booted** 에러 
<img width="830" alt="image" src="https://user-images.githubusercontent.com/51353146/198033769-d07a2e14-8444-457b-8f9f-50843103d85d.png">

`/Users/chloek/project/alarmking/node_modules/react-native-date-picker/ios/RNDatePicker/DatePicker.m error build: Build input file cannot be found: '/Users/chloek/project/alarmking/node_modules/react-native-date-picker/ios/RNDatePicker/DatePicker.m'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?`

- 첫번째 사진 처럼 빌드가 안되는 현상 발생
- `xcode` ide 로 실행했을 때 나타나는 에러에서 `DatePicker` 문제 인듯 함

**콘솔 에러 메세지**
<img width="948" alt="image" src="https://user-images.githubusercontent.com/51353146/198035215-ab006877-b40e-49b4-ad50-4a2ce958a739.png">

@hong-soohyuk 해결할 수 있는 방법 아시면 코멘트 달아주세여~

**Comment by hong-soohyuk** [comment]
첫번째 booted 팝업은 빌드에러가 아닌거같은데?
두번째 사진은 잘 모르겠는데... pod install 해봤어?

**Comment by Chloekkk** [comment]
`xcode` 를 실행 안해놔서 나타나는 알림창으로 보임

**Xcode 실행안했을 때 `yarn ios`**
1. 저 알람창 뜸
2. xcode 실행
3. 애뮬레이터로 실행

**Comment by nyeoni** [comment]
1. alert 창 같은 경우 xcode 가 실행안되어 있으면 발생
2. 두 번째 사진의 에러는 `pod install` 을 안해서 발생하는 문제
